FROM mesos-build
MAINTAINER Kevin Klues <klueska@mesosphere.com>

ENTRYPOINT ["mesos-master", \
            "--ip=127.0.0.1", \
            "--quorum=1", \
            "--work_dir=/var/lib/mesos", \
            "--log_dir=/var/log/mesos", \
            "--cluster=GPU Test Cluster"]
