FROM mesos-build
MAINTAINER David Greenberg <dgrnbrg.consulting@gmail.com>

WORKDIR /

RUN git clone https://github.com/dgrnbrg/Cook.git && curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && chmod +x lein

WORKDIR /Cook/scheduler

RUN git checkout gpu-support

COPY ../cook.jar cook.jar

ENTRYPOINT ["java", \
            "-jar", \
            "cook.jar" \
            "dev-config.edn"]
